### ISSUE TITLE
Contribution guidelines, issue template, etc.

### ISSUE THREAD

**Issue by j-andrews7** [damienmarsic/Parent-map#1]
Hi @damienmarsic,

As part of your [JOSS review](https://github.com/openjournals/joss-reviews/issues/2864), I noticed that the repo currently lacks [community guidelines for contributing](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-guidelines-for-repository-contributors), where users can find support or how to structure an issue, and a PR template. 

I'd like to see at least the first of those added, though the others may be a good idea as well.

**Comment by damienmarsic** [comment]
Hi Jared,
Thanks for your feedback. I created a CONTRIBUTING.md file, as well as bug report and feature request templates, and a discussion list.

**Comment by j-andrews7** [comment]
Excellent, thanks! I'll finish off my review throughout the week.
