### ISSUE TITLE
Basic functionality tests

### ISSUE THREAD

**Issue by j-andrews7** [damienmarsic/Parent-map#2]
**Is your feature request related to a problem? Please describe.**
Basic functionality tests would be a large boon to this package and let me tick a box for your [review](https://github.com/openjournals/joss-reviews/issues/2864).

**Describe the solution you'd like**
Testing is easy to implement via [pytest](https://docs.pytest.org/en/stable/) and can be simple.

A handful of tests to show that stats are properly calculated, deletions/insertions are handled as expected, and alignment works are all that are needed.

**Comment by damienmarsic** [comment]
Hi Jared,
I added a test_.py script which tests 4 functions (+ 2 additional functions called by one of them). I had to make changes to parent-map.py becasue it did not have a main function so pytest could not work. Before running the test_.py script you first need to update parent-map to the latest version 1.1.1 (already on bioconda).

**Comment by damienmarsic** [comment]
By the way, I was unaware of pytest and all this testing stuff. I thought the most important test was to use parent-map with real-life example. That's why I assembled a collection of  sequences from the relevant literature.

**Comment by j-andrews7** [comment]
> By the way, I was unaware of pytest and all this testing stuff. I thought the most important test was to use parent-map with real-life example. That's why I assembled a collection of sequences from the relevant literature.

Oh, the examples are critical, don't get me wrong! And you've done a good job with them. Automated testing is more for you and others who may want to contribute to development - tells you that functionally isn't being broken or altered when it shouldn't be. Imagine you want to change the code to add a feature, but it unknowingly alters the output in an unwanted manner. Now with these tests, you'd catch that and be able to address it. It's an important part of software dev and a good habit to have.

Thanks for adding them!
